/**
 * lotifySampleApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LinkRequestBody model module.
 * @module model/LinkRequestBody
 * @version 0.0.1
 */
class LinkRequestBody {
    /**
     * Constructs a new <code>LinkRequestBody</code>.
     * @alias module:model/LinkRequestBody
     * @param clientId {String} 
     * @param redirectUri {String} 
     */
    constructor(clientId, redirectUri) { 
        
        LinkRequestBody.initialize(this, clientId, redirectUri);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, clientId, redirectUri) { 
        obj['client_id'] = clientId;
        obj['redirect_uri'] = redirectUri;
    }

    /**
     * Constructs a <code>LinkRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LinkRequestBody} obj Optional instance to populate.
     * @return {module:model/LinkRequestBody} The populated <code>LinkRequestBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LinkRequestBody();

            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('redirect_uri')) {
                obj['redirect_uri'] = ApiClient.convertToType(data['redirect_uri'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} client_id
 */
LinkRequestBody.prototype['client_id'] = undefined;

/**
 * @member {String} redirect_uri
 */
LinkRequestBody.prototype['redirect_uri'] = undefined;

/**
 * @member {String} state
 */
LinkRequestBody.prototype['state'] = undefined;






export default LinkRequestBody;

