/**
 * lotifySampleApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CodeRequestBody from '../model/CodeRequestBody';
import CodeResponse from '../model/CodeResponse';

/**
* Code service.
* @module api/CodeApi
* @version 0.0.1
*/
export default class CodeApi {

    /**
    * Constructs a new CodeApi. 
    * @alias module:api/CodeApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the codeChangeToken operation.
     * @callback module:api/CodeApi~codeChangeTokenCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CodeResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Change token
     * @param {module:model/CodeRequestBody} body Code
     * @param {module:api/CodeApi~codeChangeTokenCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CodeResponse}
     */
    codeChangeToken(body, callback) {
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling codeChangeToken");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*', 'application/json'];
      let returnType = CodeResponse;
      return this.apiClient.callApi(
        '/notify/change', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
