/**
 * lotifySampleApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import NotifyResponse from '../model/NotifyResponse';
import TextRequestBody from '../model/TextRequestBody';

/**
* Text service.
* @module api/TextApi
* @version 0.0.1
*/
export default class TextApi {

    /**
    * Constructs a new TextApi. 
    * @alias module:api/TextApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the sendText operation.
     * @callback module:api/TextApi~sendTextCallback
     * @param {String} error Error message, if any.
     * @param {module:model/NotifyResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Send LINE Noitfy text message
     * @param {module:model/TextRequestBody} body Send LINE Noitfy text message
     * @param {module:api/TextApi~sendTextCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/NotifyResponse}
     */
    sendText(body, callback) {
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling sendText");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*', 'application/json'];
      let returnType = NotifyResponse;
      return this.apiClient.callApi(
        '/notify/send', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
