/**
 * lotifySampleApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CodeRequestBody from './model/CodeRequestBody';
import CodeResponse from './model/CodeResponse';
import ImageUrlRequestBody from './model/ImageUrlRequestBody';
import LinkRequestBody from './model/LinkRequestBody';
import LinkResponse from './model/LinkResponse';
import NotifyResponse from './model/NotifyResponse';
import RevokeRequestBody from './model/RevokeRequestBody';
import StickerRequestBody from './model/StickerRequestBody';
import TextRequestBody from './model/TextRequestBody';
import CodeApi from './api/CodeApi';
import ImageApi from './api/ImageApi';
import LinkApi from './api/LinkApi';
import RevokeApi from './api/RevokeApi';
import StickerApi from './api/StickerApi';
import TextApi from './api/TextApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var LotifySampleApi = require('index'); // See note below*.
* var xxxSvc = new LotifySampleApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new LotifySampleApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new LotifySampleApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new LotifySampleApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CodeRequestBody model constructor.
     * @property {module:model/CodeRequestBody}
     */
    CodeRequestBody,

    /**
     * The CodeResponse model constructor.
     * @property {module:model/CodeResponse}
     */
    CodeResponse,

    /**
     * The ImageUrlRequestBody model constructor.
     * @property {module:model/ImageUrlRequestBody}
     */
    ImageUrlRequestBody,

    /**
     * The LinkRequestBody model constructor.
     * @property {module:model/LinkRequestBody}
     */
    LinkRequestBody,

    /**
     * The LinkResponse model constructor.
     * @property {module:model/LinkResponse}
     */
    LinkResponse,

    /**
     * The NotifyResponse model constructor.
     * @property {module:model/NotifyResponse}
     */
    NotifyResponse,

    /**
     * The RevokeRequestBody model constructor.
     * @property {module:model/RevokeRequestBody}
     */
    RevokeRequestBody,

    /**
     * The StickerRequestBody model constructor.
     * @property {module:model/StickerRequestBody}
     */
    StickerRequestBody,

    /**
     * The TextRequestBody model constructor.
     * @property {module:model/TextRequestBody}
     */
    TextRequestBody,

    /**
    * The CodeApi service constructor.
    * @property {module:api/CodeApi}
    */
    CodeApi,

    /**
    * The ImageApi service constructor.
    * @property {module:api/ImageApi}
    */
    ImageApi,

    /**
    * The LinkApi service constructor.
    * @property {module:api/LinkApi}
    */
    LinkApi,

    /**
    * The RevokeApi service constructor.
    * @property {module:api/RevokeApi}
    */
    RevokeApi,

    /**
    * The StickerApi service constructor.
    * @property {module:api/StickerApi}
    */
    StickerApi,

    /**
    * The TextApi service constructor.
    * @property {module:api/TextApi}
    */
    TextApi
};
